local mark = require("harpoon.mark")
local ui = require("harpoon.ui")
local term = require("harpoon.term")
local cmd = require("harpoon.cmd-ui")

vim.keymap.set("n", "<leader>a", mark.add_file, { desc = "Harpoon [a]dd file" })
vim.keymap.set("n", "<leader>h", ui.toggle_quick_menu, { desc = "[H]arpoon menu" })

vim.keymap.set("n", "<tab>u", function()
	ui.nav_file(1)
end, { desc = "Go to file 1" })
vim.keymap.set("n", "<tab>i", function()
	ui.nav_file(2)
end, { desc = "Go to file 2" })
vim.keymap.set("n", "<tab>o", function()
	ui.nav_file(3)
end, { desc = "Go to file 3" })
vim.keymap.set("n", "<tab>p", function()
	ui.nav_file(4)
end, { desc = "Go to file 4" })
vim.keymap.set("n", "<tab>j", function()
	ui.nav_next()
end, { desc = "Go to the next file" })
vim.keymap.set("n", "<tab>k", function()
	ui.nav_prev()
end, { desc = "Go to the previous file" })

vim.keymap.set("n", "<tab>g", function()
	term.gotoTerminal(1)
end, { desc = "Go to the term 1" })
vim.keymap.set("n", "<tab>h", function()
	term.gotoTerminal(2)
end, { desc = "Go to the term 2" })

vim.keymap.set("n", "<tab>g1", function()
	term.sendCommand(1, 1)
end, { desc = "Send command 1 to term 1" })
vim.keymap.set("n", "<tab>g2", function()
	term.sendCommand(2, 1)
end, { desc = "Send command 2 to term 1" })
vim.keymap.set("n", "<tab>h1", function()
	term.sendCommand(1, 2)
end, { desc = "Send command 1 to term 2" })
vim.keymap.set("n", "<tab>h2", function()
	term.sendCommand(2, 2)
end, { desc = "Send command 2 to term 2" })

vim.keymap.set("n", "<leader>H", function()
	cmd.toggle_quick_menu()
end, { desc = "[H]arpoon commands menu" })
